---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OM_TARGET:
  OM_USERNAME:
  OM_PASSWORD:
  OM_CLIENT_ID:
  OM_CLIENT_SECRET:
  IAAS_CONFIGURATION:
  DIRECTOR_CONFIGURATION:
  AZ_CONFIGURATION:
  NETWORK_CONFIGURATION:
  NETWORK_ASSIGNMENT:
  SECURITY_CONFIGURATION:
  RESOURCE_CONFIGURATION:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-opsdir/task.sh
