resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: jq
  type: github-release
  source:
    user: stedolan
    repository: jq
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

#- name: cf
#  type: github-release
#  source:
#    user: cloudfoundry
#    repository: cli
#    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pipelines-repo
  type: git
  source:
    uri: ((git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))
    skip_ssl_verification: true


- name: pivnet-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((product_name))
    product_version: ((product_version))

jobs:

- name: delete-product
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs:
        - "*.pivotal"
    - get: om-cli
      params:
        globs:
        - "*-linux*[^.tar.gz]"

  - task: unstage-tile
    file: pipelines-repo/tasks/unstage-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PRODUCT_IDENTIFIER: ((product_identifier))

  - task: apply-changes
    file: pipelines-repo/tasks/apply-changes/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))

- name: upload-product
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs:
        - "*.pivotal"
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux*[^.tar.gz]"
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
    - get: jq
      params:
        globs:
        - "*linux64*"

  - task: upload-tile
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))

- name: stage-product
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-product]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs:
        - "*.pivotal"
      passed: [upload-product]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux*[^.tar.gz]"
      passed: [upload-product]

  - task: stage-tile
    file: pipelines-repo/tasks/stage-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PRODUCT_IDENTIFIER: ((product_identifier))

- name: config-product
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [stage-product]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs: []
        save: true
      passed: [stage-product]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux*[^.tar.gz]"
      passed: [stage-product]
    - get: jq
      params:
        globs:
        - "*linux64*"
      passed: [upload-product]

  - task: config-tile
    file: pipelines-repo/tasks/config-p-push-notifications/task.yml
    params:
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd)) 
      NETWORK_NAME: ((network_name))
      SERVICE_NETWORK_NAME: ((service_network_name))
      OTHER_AZS: ((other_azs))
      SINGLETON_JOBS_AZ: ((singleton_jobs_az))
      PRODUCT_IDENTIFIER: ((product_identifier))
      APNS_PROXY: ((apns_proxy)) 
      APNS_PROXY_SOCKS_HOST: ((apns_proxy_socks_host)) 
      APNS_PROXY_SOCKS_PORT: ((apns_proxy_socks_port))
      BAIDU_PROXY: ((baidu_proxy))
      BAIDU_PROXY_HTTP_HOST: ((baidu_proxy_http_host))
      BAIDU_PROXY_HTTP_PORT: ((baidu_proxy_http_port))
      BAIDU_PROXY_SOCKS_HOST: ((baidu_proxy_socks_host))
      BAIDU_PROXY_SOCKS_PORT: ((baidu_proxy_socks_port))
      CREATE_PLATFORM_WHITELIST: ((create_platform_whitelist))
      DEPLOYMENT_TYPE: ((deployment_type))
      FCM_PROXY: ((fcm_proxy))
      FCM_PROXY_HTTP_HOST: ((fcm_proxy_http_host))
      FCM_PROXY_HTTP_PORT: ((fcm_proxy_http_port))
      FCM_PROXY_SOCKS_HOST: ((fcm_proxy_socks_host))
      FCM_PROXY_SOCKS_PORT: ((fcm_proxy_socks_port))
      GCM_PROXY: ((gcm_proxy))
      GCM_PROXY_HTTP_HOST: ((gcm_proxy_http_host))
      GCM_PROXY_HTTP_PORT: ((gcm_proxy_http_port))
      GCM_PROXY_SOCKS_HOST: ((gcm_proxy_socks_host))
      GCM_PROXY_SOCKS_PORT: ((gcm_proxy_socks_port))
      MYSQL: ((mysql))
      MYSQL_EXTERNAL_DATABASE: ((mysql_external_database))
      MYSQL_EXTERNAL_HOST: ((mysql_external_host))
      MYSQL_EXTERNAL_PASSWORD: ((mysql_external_password))
      MYSQL_EXTERNAL_PORT: ((mysql_external_port))
      MYSQL_EXTERNAL_USERNAME: ((mysql_external_username))
      MYSQL_INTERNAL_SERVICE_PLAN: ((mysql_internal_service_plan))
      REDIS_ANALYTICS: ((redis_analytics))
      REDIS_ANALYTICS_EXTERNAL_DB_NUMBER: ((redis_analytics_external_db_number))
      REDIS_ANALYTICS_EXTERNAL_HOST: ((redis_analytics_external_host))
      REDIS_ANALYTICS_EXTERNAL_PASSWORD: ((redis_analytics_external_password))
      REDIS_ANALYTICS_EXTERNAL_PORT: ((redis_analytics_external_port))
      REDIS_ANALYTICS_INTERNAL_SERVICE_PLAN: ((redis_analytics_internal_service_plan))
      PUSH_PUSH_NOTIFICATIONS_API_DB_ENCRYPTION_KEY: ((push_push_notifications_api_db_encryption_key))
      PUSH_PUSH_NOTIFICATIONS_DEFAULT_SYSTEM_TENANT_NAME: ((push_push_notifications_default_system_tenant_name))

- name: disable-errands
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [config-product]
    - get: om-cli
      params:
        globs:
        - "*om-linux*[^.tar.gz]"
      passed: [config-product]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs: []
      passed: [config-product]
      trigger: true
    - get: jq
      params:
        globs:
        - "*linux64*"
      passed: [config-product]

  - task: disable-errands
    file: pipelines-repo/tasks/disable-errands/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PRODUCT_IDENTIFIER: ((product_identifier))
      ERRANDS: ((errands_to_disable))

- name: apply-changes
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [disable-errands]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs: []
      passed: [disable-errands]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux*[^.tar.gz]"
      passed: [disable-errands]

  - task: apply-changes
    file: pipelines-repo/tasks/apply-changes/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))

- name: set-upgrade-pipeline
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [apply-changes]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs: []
      passed: [apply-changes]
      trigger: true

  - task: set-upgrade-pipeline
    file: pipelines-repo/tasks/set-upgrade-pipeline/task.yml
    params:
      DEBUG: ((debug))
      CONCOURSE_USERNAME: ((concourse_user))
      CONCOURSE_PASSWD: ((concourse_pwd))
      CONCOURSE_URL: ((concourse_url))
      BUILD_PIPELINE_NAME: ((pipeline-name))
      BUILD_TEAM_NAME: ((team-name))
      UPGRADE_PIPELINE_NAME: ((upgrade-pipeline-name))
      PRODUCT_NAME: ((product_name))
      PRODUCT_IDENTIFIER: ((product_identifier))
      PRODUCT_VERSION: ((product_version))
