---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  SERVICE_NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_IDENTIFIER:
  APNS_PROXY:
  APNS_PROXY_SOCKS_HOST:
  APNS_PROXY_SOCKS_PORT:
  BAIDU_PROXY:
  BAIDU_PROXY_HTTP_HOST:
  BAIDU_PROXY_HTTP_PORT:
  BAIDU_PROXY_SOCKS_HOST:
  BAIDU_PROXY_SOCKS_PORT:
  CREATE_PLATFORM_WHITELIST:
  DEPLOYMENT_TYPE:
  FCM_PROXY:
  FCM_PROXY_HTTP_HOST:
  FCM_PROXY_HTTP_PORT:
  FCM_PROXY_SOCKS_HOST:
  FCM_PROXY_SOCKS_PORT:
  GCM_PROXY:
  GCM_PROXY_HTTP_HOST:
  GCM_PROXY_HTTP_PORT:
  GCM_PROXY_SOCKS_HOST:
  GCM_PROXY_SOCKS_PORT:
  MYSQL:
  MYSQL_EXTERNAL_DATABASE:
  MYSQL_EXTERNAL_HOST:
  MYSQL_EXTERNAL_PASSWORD:
  MYSQL_EXTERNAL_PORT:
  MYSQL_EXTERNAL_USERNAME:
  MYSQL_INTERNAL_SERVICE_PLAN:
  REDIS_ANALYTICS:
  REDIS_ANALYTICS_EXTERNAL_DB_NUMBER:
  REDIS_ANALYTICS_EXTERNAL_HOST:
  REDIS_ANALYTICS_EXTERNAL_PASSWORD:
  REDIS_ANALYTICS_EXTERNAL_PORT:
  REDIS_ANALYTICS_INTERNAL_SERVICE_PLAN:
  PUSH_PUSH_NOTIFICATIONS_API_DB_ENCRYPTION_KEY:
  PUSH_PUSH_NOTIFICATIONS_DEFAULT_SYSTEM_TENANT_NAME:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-p-push-notifications/task.sh
