pivnet_token: ((pivnet_token)) # [R] PivNet Access Token
git_token: ((github_token)) # [R] Your github token
git_url: https://github.com/rahul-kj/pcf-concourse-pipelines # [R] Pipelines github repo
git_branch: master
git_username: ((github_username)) # [R] Your github username

iaas_type: vsphere-esxi # azure-hyperv|vsphere-esxi|aws-xen-hvm|openstack-kvm|vcloud-esxi|google-kvm

## Ops Manager installation meta data
ops_mgr_host: ((ops_mgr_host)) # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: ((ops_mgr_usr)) # [R] Ops Manager admin user
ops_mgr_pwd: ((ops_mgr_pwd)) # [R] Ops Manager admin password

debug: true
product_name: p-new-relic
product_identifier: newrelic-broker
product_version: ^1\.12\..*$

singleton_jobs_az: ((singleton_jobs_az)) # [R] Place singleton jobs in an AZ
other_azs: ((other_azs))         # [R] Balance other jobs in AZ's (comma-separated)
network_name: ((network_name))      # [R] Tile network name

allow_paid_service_plans: false
app_name: "NewRelicServiceBroker"
app_uri: "newrelic-broker"
app_version: "v1.12.9"
apply_open_security_group: false
newrelic_broker_enable_global_access_to_plans: true
nrplans: '{\"planName\":\"dev\",\"planDescription\":\"dev plan\",\"licenseKey\":\"SOMELICENSEKEY\"}'
org: "NewRelicServiceBroker-service-org"
space: "NewRelicServiceBroker-service-space"

errands_to_disable:

concourse_url: ((concourse_url))
concourse_user: ((concourse_user))
concourse_pwd: ((concourse_pwd))

pipeline-name: install-newrelic-service-broker
team-name: ((team-name))
upgrade-pipeline-name: upgrade-newrelic-service-broker
