---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OM_TARGET:
  OM_USERNAME:
  OM_PASSWORD:
  OM_CLIENT_ID:
  OM_CLIENT_SECRET:
  PIVNET_API_TOKEN:
  REPLICATOR_NAME:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: pivnet-product
  - name: replicator

outputs:
  - name: replicator-tile

run:
  path: pipelines-repo/tasks/replicate-and-upload-tile/task.sh
