# Token used to download the product file from Pivotal Network. Find this
# on your Pivotal Network profile page:
# https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: ((pivnet_token)) # [R] PivNet Access Token
git_token: ((github_token)) # [R] Your github token
git_url: https://github.com/rahul-kj/pcf-concourse-pipelines # [R] Pipelines github repo
git_branch: master
git_username: ((github_username)) # [R] Your github username

iaas_type: vsphere-esxi # azure-hyperv|vsphere-esxi|aws-xen-hvm|openstack-kvm|vcloud-esxi|google-kvm

debug: false

## Ops Manager installation meta data
ops_mgr_host: ((ops_mgr_host)) # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: ((ops_mgr_usr))  # [R] Ops Manager admin user
ops_mgr_pwd: ((ops_mgr_pwd))  # [R] Ops Manager admin password

product_name: splunk-nozzle
product_identifier: splunk-nozzle
product_version: ^1\.0\..*$

singleton_jobs_az: ((singleton_jobs_az)) # [R] Place singleton jobs in an AZ
other_azs: ((other_azs))         # [R] Balance other jobs in AZ's (comma-separated)
network_name: ((network_name))      # [R] Tile network name

add_app_info: false # true|false
allow_paid_service_plans: true # true|false
api_endpoint:
api_password:
api_user:
apply_open_security_group: true # true|false
enable_event_tracing: false # true|false
events: HttpStartStop,LogMessage,ValueMetric,CounterEvent,Error,ContainerMetric
extra_fields:
firehose_subscription_id:
org: "splunk-nozzle-org"
scale_out_nozzle: 2
skip_ssl_validation_cf: false # true|false
skip_ssl_validation_splunk: false # true|false
space: "splunk-nozzle-space"
splunk_host:
splunk_index:
splunk_token:

errands_to_disable:

concourse_url: ((concourse_url))
concourse_user: ((concourse_user))
concourse_pwd: ((concourse_pwd))

pipeline-name: install-splunk-nozzle
team-name: ((team-name))
upgrade-pipeline-name: upgrade-splunk-nozzle
