---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OM_TARGET:
  OM_USERNAME:
  OM_PASSWORD:
  OM_CLIENT_ID:
  OM_CLIENT_SECRET:
  PRODUCT_NAME:
  DEPENDENCY_PRODUCT_TILES:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: pivnet-product

run:
  path: pipelines-repo/tasks/stage-product/task.sh
