---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OM_TARGET:
  OM_USERNAME:
  OM_PASSWORD:
  OM_CLIENT_ID:
  OM_CLIENT_SECRET:
  GENERATE_CERTS:
  PRODUCT_PROPERTIES:
  RESOURCE_CONFIG:
  NETWORK_PROPERTIES:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-ert/task.sh
