resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: jq
  type: github-release
  source:
    user: stedolan
    repository: jq
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: tile-config-convertor
  type: github-release
  source:
    user: rahul-kj
    repository: tile-config-convertor
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pipelines-repo
  type: git
  source:
    uri: ((git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))

- name: pivnet-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((product_slug))
    product_version: ((product_version))

jobs:

- name: delete-product
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs:
        - "*.pivotal"
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: jq
      params:
        globs:
        - "*linux64*"

  - task: unstage-tile
    file: pipelines-repo/tasks/unstage-product/task.yml
    params:
      DEBUG: ((debug))
      OM_TARGET: ((ops_mgr_host))
      OM_USERNAME: ((ops_mgr_usr))
      OM_PASSWORD: ((ops_mgr_pwd))
      OM_CLIENT_ID: ((opsman_client_id))
      OM_CLIENT_SECRET: ((opsman_client_secret))
      PRODUCT_NAME: ((product-name))

  - task: apply-changes
    file: pipelines-repo/tasks/apply-changes/task.yml
    params:
      DEBUG: ((debug))
      OM_TARGET: ((ops_mgr_host))
      OM_USERNAME: ((ops_mgr_usr))
      OM_PASSWORD: ((ops_mgr_pwd))
      OM_CLIENT_ID: ((opsman_client_id))
      OM_CLIENT_SECRET: ((opsman_client_secret))
      APPLY_CHANGES_CONFIG: ""

- name: upload-product
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs:
        - "*.pivotal"
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
    - get: jq
      params:
        globs:
        - "*linux64*"

  - task: upload-tile
    file: pipelines-repo/tasks/upload-product/task.yml
    input_mapping:
      product: pivnet-product
    params:
      DEBUG: ((debug))
      OM_TARGET: ((ops_mgr_host))
      OM_USERNAME: ((ops_mgr_usr))
      OM_PASSWORD: ((ops_mgr_pwd))
      OM_CLIENT_ID: ((opsman_client_id))
      OM_CLIENT_SECRET: ((opsman_client_secret))

  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      DEBUG: ((debug))
      OM_TARGET: ((ops_mgr_host))
      OM_USERNAME: ((ops_mgr_usr))
      OM_PASSWORD: ((ops_mgr_pwd))
      OM_CLIENT_ID: ((opsman_client_id))
      OM_CLIENT_SECRET: ((opsman_client_secret))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS: ((iaas))
      IAAS_TYPE: ((iaas_type))
      STEMCELL_TYPE: ((stemcell_type))

- name: generate-product-config
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [stage-product]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs: []
      passed: [stage-product]
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [stage-product]
    - get: jq
      params:
        globs:
        - "*linux64*"
      passed: [upload-product]
    - get: tile-config-convertor
      params:
        globs: ["*linux*"]

  - task: generate-config
    file: pipelines-repo/tasks/generate-config/task.yml
    params:
      DEBUG: ((debug))
      OM_TARGET: ((ops_mgr_host))
      OM_USERNAME: ((ops_mgr_usr))
      OM_PASSWORD: ((ops_mgr_pwd))
      OM_CLIENT_ID: ((opsman_client_id))
      OM_CLIENT_SECRET: ((opsman_client_secret))
      PRODUCT_NAME: ((product-name))

- name: stage-product
  plan:
  - aggregate:
    - get: pipelines-repo
      # passed: [upload-product]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs: []
      passed: [upload-product]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-product]

  - task: stage-tile
    file: pipelines-repo/tasks/stage-product/task.yml
    params:
      DEBUG: ((debug))
      OM_TARGET: ((ops_mgr_host))
      OM_USERNAME: ((ops_mgr_usr))
      OM_PASSWORD: ((ops_mgr_pwd))
      OM_CLIENT_ID: ((opsman_client_id))
      OM_CLIENT_SECRET: ((opsman_client_secret))
      PRODUCT_NAME: ((product-name))
      DEPENDENCY_PRODUCT_TILES: ((dependency_product_tiles))

- name: config-product
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [stage-product]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs: []
      passed: [stage-product]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [stage-product]
    - get: jq
      params:
        globs:
        - "*linux64*"
      passed: [upload-product]

  - task: config-tile
    file: pipelines-repo/tasks/config-product/task.yml
    params:
      DEBUG: ((debug))
      OM_TARGET: ((ops_mgr_host))
      OM_USERNAME: ((ops_mgr_usr))
      OM_PASSWORD: ((ops_mgr_pwd))
      OM_CLIENT_ID: ((opsman_client_id))
      OM_CLIENT_SECRET: ((opsman_client_secret))
      PRODUCT_NAME: ((product-name))
      PRODUCT_PROPERTIES: ((product-properties))
      RESOURCE_CONFIG: ((resource-config))
      NETWORK_PROPERTIES: ((network-properties))

- name: disable-errands
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [config-product]
    - get: om-cli
      params:
        globs:
        - "*om-linux*"
      passed: [config-product]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs: []
      passed: [config-product]
      trigger: true
    - get: jq
      params:
        globs:
        - "*linux64*"
      passed: [config-product]

  - task: disable-errands
    file: pipelines-repo/tasks/disable-errands/task.yml
    params:
      DEBUG: ((debug))
      OM_TARGET: ((ops_mgr_host))
      OM_USERNAME: ((ops_mgr_usr))
      OM_PASSWORD: ((ops_mgr_pwd))
      OM_CLIENT_ID: ((opsman_client_id))
      OM_CLIENT_SECRET: ((opsman_client_secret))
      PRODUCT_NAME: ((product-name))
      ERRANDS: ((errands_to_disable))

- name: apply-changes
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [disable-errands]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs: []
      passed: [disable-errands]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [disable-errands]
    - get: jq
      params:
        globs:
        - "*linux64*"
      passed: [disable-errands]

  - task: apply-changes
    file: pipelines-repo/tasks/apply-changes/task.yml
    params:
      DEBUG: ((debug))
      OM_TARGET: ((ops_mgr_host))
      OM_USERNAME: ((ops_mgr_usr))
      OM_PASSWORD: ((ops_mgr_pwd))
      OM_CLIENT_ID: ((opsman_client_id))
      OM_CLIENT_SECRET: ((opsman_client_secret))
      APPLY_CHANGES_CONFIG: ((apply_changes_config))
